# Generated by Django 5.0.1 on 2024-01-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enias.pagina')),
            ],
        ),
    ]
