# Generated by Django 5.0.1 on 2024-01-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enias', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='textos',
        ),
        migrations.CreateModel(
            name='Caixa_de_texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textos', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id_pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enias.pagina')),
            ],
        ),
    ]
