# Generated by Django 5.0.1 on 2024-01-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enias', '0003_remove_pagina_textos_caixa_de_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
